### PR TITLE
give joins a name

### PR DESCRIPTION
**Pull request by danfrankj**
For readability and query caching (in omniduct)

### CODE REVIEW

**Comment by matthewwardrop** [comment]
This may make join names non-unique if the same provider is used twice in different contexts (for example, see `test_forward_joins` in the strategy unit tests), which is why I avoided using the provider name there. What I had thought to do is a hash on the actual content of the query; but we should get by if we just append the unit_type to the name of the join (e.g. "<provider_name>_<unit_type>_<join>").

**Comment by danfrankj** [comment]
@matthewwardrop that does make sense ... I've added the unittype. Should work for most cases. All cases?

**Comment by matthewwardrop** [comment]
Should be all cases. A unit provider should only be directly evaluated once per target unit_type in the context of a particular join set. The same name may be used elsewhere in the query, but in a different context, and so that probably wouldn't matter.

**Comment by matthewwardrop** [comment]
I changed the default name assigned to a Join class in master, rather than explicitly doing it here. I think that's probably the right place to do it.

**Pull request closed without merging**
